import { useAuth } from '@/context/auth';
import { useDiary } from '@/context/diary';
import { usePremiumTheme } from '@/context/theme';
import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';

const FIELDS = [{ key: 'weight', label: 'Peso', unit: 'kg', icon: 'scale-outline' as const }, { key: 'waist', label: 'Cintura', unit: 'cm', icon: 'resize-outline' as const }, { key: 'hip', label: 'Quadril', unit: 'cm', icon: 'body-outline' as const }, { key: 'arm', label: 'Braço', unit: 'cm', icon: 'barbell-outline' as const }, { key: 'bodyFat', label: '% Gordura', unit: '%', icon: 'analytics-outline' as const }];
export default function TrackingScreen() {
  const { colors: C } = usePremiumTheme(); const { updateUser } = useAuth(); const { measurements, addMeasurement } = useDiary(); const [form, setForm] = useState<Record<string, string>>({});
  const save = async () => { if (!Object.values(form).some(Boolean)) return Alert.alert('Sem medidas', 'Informe pelo menos uma medida para salvar.'); await addMeasurement(form); if (form.weight) updateUser({ weight: form.weight.replace(',', '.') }); setForm({}); Alert.alert('Registro salvo', 'Suas medidas foram registradas no aparelho.'); };
  const card = { backgroundColor: C.surface, borderRadius: 20, padding: 18, borderWidth: 1, borderColor: C.border } as const;
  return <ScrollView style={{ flex: 1, backgroundColor: C.bg }} contentContainerStyle={{ padding: 20, gap: 16, paddingBottom: 50 }}><View style={card}><Text style={{ fontSize: 18, fontWeight: '900', color: C.text }}>Medidas corporais</Text><Text style={{ color: C.textMuted, marginTop: 4, marginBottom: 15 }}>Registre apenas o que você mediu hoje.</Text>{FIELDS.map(field => <View key={field.key} style={{ flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.surface2, borderRadius: 13, padding: 12, marginBottom: 9 }}><Ionicons name={field.icon} size={19} color={C.primary} /><Text style={{ width: 82, color: C.text, fontWeight: '700' }}>{field.label}</Text><TextInput value={form[field.key] || ''} onChangeText={value => setForm(prev => ({ ...prev, [field.key]: value }))} keyboardType="decimal-pad" placeholder="—" placeholderTextColor={C.textDim} style={{ flex: 1, color: C.text, textAlign: 'right', fontWeight: '700', fontSize: 15 }} /><Text style={{ color: C.textMuted, width: 28 }}>{field.unit}</Text></View>)}</View><TouchableOpacity onPress={save} style={{ backgroundColor: C.primary, padding: 16, borderRadius: 14, alignItems: 'center' }}><Text style={{ color: '#fff', fontSize: 16, fontWeight: '800' }}>Salvar registro</Text></TouchableOpacity><View style={card}><Text style={{ color: C.text, fontSize: 16, fontWeight: '800', marginBottom: 8 }}>Últimos registros</Text>{measurements.length === 0 ? <Text style={{ color: C.textMuted, paddingVertical: 12 }}>Nenhuma medida registrada ainda.</Text> : measurements.slice(-5).reverse().map(record => <View key={record.id} style={{ paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: C.border }}><Text style={{ color: C.textMuted, fontSize: 12 }}>{new Date(record.createdAt).toLocaleDateString('pt-BR')}</Text><Text style={{ color: C.text, fontWeight: '700', marginTop: 3 }}>{[record.weight && `${record.weight} kg`, record.waist && `cintura ${record.waist} cm`, record.hip && `quadril ${record.hip} cm`].filter(Boolean).join(' · ')}</Text></View>)}</View></ScrollView>;
}
