import { useDiary } from '@/context/diary';
import { useAppLayout } from '@/hooks/useAppLayout';
import { usePremiumTheme } from '@/context/theme';
import { Ionicons } from '@expo/vector-icons';
import { ScrollView, Text, View } from 'react-native';

export default function HistoryScreen() {
  const { allMeals, ready } = useDiary(); const { colors: C } = usePremiumTheme(); const { topPad } = useAppLayout();
  const entries = Object.values(allMeals.reduce<Record<string, { date: Date; calories: number; meals: number }>>((acc, meal) => { const date = new Date(meal.createdAt); const key = date.toLocaleDateString('en-CA'); acc[key] ??= { date, calories: 0, meals: 0 }; acc[key].calories += meal.calories; acc[key].meals += 1; return acc; }, {})).sort((a, b) => b.date.getTime() - a.date.getTime());
  return <ScrollView style={{ flex: 1, backgroundColor: C.bg }} contentContainerStyle={{ padding: 20, paddingTop: topPad, gap: 10, paddingBottom: 100 }}><Text style={{ fontSize: 26, fontWeight: '900', color: C.text }}>Histórico</Text><Text style={{ fontSize: 14, color: C.textMuted, marginBottom: 10 }}>Dias em que você registrou refeições.</Text>{!ready ? <Text style={{ color: C.textMuted }}>Carregando registros…</Text> : entries.length === 0 ? <View style={{ backgroundColor: C.surface, padding: 30, borderRadius: 20, alignItems: 'center', gap: 8 }}><Ionicons name="calendar-outline" size={35} color={C.textDim} /><Text style={{ color: C.text, fontWeight: '800' }}>Nenhum histórico ainda</Text><Text style={{ color: C.textMuted, textAlign: 'center' }}>O histórico aparece quando você registrar refeições.</Text></View> : entries.map(entry => <View key={entry.date.toISOString()} style={{ backgroundColor: C.surface, borderRadius: 16, padding: 16, flexDirection: 'row', alignItems: 'center' }}><View style={{ flex: 1 }}><Text style={{ color: C.text, fontWeight: '800', fontSize: 15 }}>{entry.date.toLocaleDateString('pt-BR', { weekday: 'long', day: 'numeric', month: 'long' })}</Text><Text style={{ color: C.textMuted, marginTop: 3 }}>{entry.meals} {entry.meals === 1 ? 'refeição registrada' : 'refeições registradas'}</Text></View><Text style={{ color: C.primary, fontWeight: '900' }}>{entry.calories} kcal</Text></View>)}</ScrollView>;
}
